FROM python:3.10-slim

WORKDIR /app

COPY ../frontend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../frontend .

CMD ["streamlit", "run", "app.py", "--server.port=8501"]